-- ==================================================================
-- 🚀 SETUP MÍNIMO DE EMERGÊNCIA - GOLDEN
-- ==================================================================
-- Use este script se o FULL estiver dando erro de conexão.
-- Ele cria apenas o essencial para o sistema funcionar agora.

-- 1. TABELA DE USUÁRIOS
CREATE TABLE IF NOT EXISTS public.app_users (
    email text PRIMARY KEY,
    name text NOT NULL,
    role text DEFAULT 'user',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_login timestamp with time zone
);

ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access users" ON public.app_users;
CREATE POLICY "Enable all access users" ON public.app_users FOR ALL USING (true) WITH CHECK (true);

-- 2. TABELA DE PEDIDOS
create table if not exists public.orders (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date text,
  salesperson text,
  classification text,
  classification_other text,
  status text,
  customer_name text,
  customer_document text,
  customer_phone text,
  customer_email text,
  billing_address jsonb,
  collection_address jsonb,
  delivery_address jsonb,
  global_value_1 numeric,
  discount_total numeric,
  freight_value numeric,
  global_value_2 numeric,
  total_amount numeric,
  total_weight numeric,
  currency_conversion text,
  exchange_rate numeric,
  total_in_brl numeric,
  min_billing boolean,
  min_billing_value numeric,
  final_customer boolean,
  payment_terms text,
  delivery_time text,
  validity text,
  valid_until text,
  bidding_number text,
  bidding_date text,
  commitment_number text,
  commitment_date text,
  notes text,
  created_by text
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for orders" ON public.orders;
DROP POLICY IF EXISTS "Enable all for orders (exclude deleted)" ON public.orders;
DROP POLICY IF EXISTS "Select orders (exclude deleted)" ON public.orders;
CREATE POLICY "Enable all for orders emergency" ON public.orders FOR ALL USING (true) WITH CHECK (true);

-- 3. TABELA DE ITENS
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text references public.orders(id) on delete cascade,
  code text,
  ncm text,
  description text,
  unit text,
  weight numeric,
  quantity numeric,
  unit_price numeric,
  total numeric
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for items" ON public.order_items;
CREATE POLICY "Enable all for items emergency" ON public.order_items FOR ALL USING (true) WITH CHECK (true);

-- 4. TABELA DE CONTATOS
create table if not exists public.order_contacts (
  id bigint generated by default as identity primary key,
  order_id text references public.orders(id) on delete cascade,
  name text,
  job_title text,
  department text,
  phone text,
  email text
);

ALTER TABLE public.order_contacts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for contacts" ON public.order_contacts;
CREATE POLICY "Enable all for contacts emergency" ON public.order_contacts FOR ALL USING (true) WITH CHECK (true);

-- FIM DO SETUP MÍNIMO
