-- TABELA DE PEDIDOS (Cria se não existir)
create table if not exists public.orders (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date text,
  salesperson text,
  classification text,
  classification_other text,
  status text,
  customer_name text,
  customer_document text,
  customer_phone text,
  customer_email text,
  customer_birthday text,
  billing_address jsonb,
  collection_address jsonb,
  delivery_address jsonb,
  global_value_1 numeric,
  discount_total numeric,
  freight_value numeric,
  global_value_2 numeric,
  total_amount numeric,
  total_weight numeric,
  currency_conversion text,
  exchange_rate numeric,
  total_in_brl numeric,
  min_billing boolean,
  min_billing_value numeric,
  final_customer boolean,
  payment_terms text,
  delivery_time text,
  validity text,
  valid_until text,
  bidding_number text,
  bidding_date text,
  commitment_number text,
  commitment_date text,
  notes text,
  created_by text,          -- Email do usuário criador
  pdf_url text,            -- URL do PDF gerado
  pdf_generated_at text    -- Data da geração do PDF
);

-- TABELA DE ITENS (Cria se não existir)
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text references public.orders(id) on delete cascade,
  code text,
  ncm text,
  description text,
  unit text,
  weight numeric,
  quantity numeric,
  unit_price numeric,
  total numeric
);

-- TABELA DE CONTATOS (Cria se não existir)
create table if not exists public.order_contacts (
  id bigint generated by default as identity primary key,
  order_id text references public.orders(id) on delete cascade,
  name text,
  job_title text,
  department text,
  phone text,
  email text,
  birthday text
);

-- HABILITAR RLS (Segurança)
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_contacts enable row level security;

-- POLÍTICAS DE ACESSO (Drop e Recria para garantir)
drop policy if exists "Enable all for orders" on public.orders;
create policy "Enable all for orders" on public.orders for all using (true) with check (true);

drop policy if exists "Enable all for items" on public.order_items;
create policy "Enable all for items" on public.order_items for all using (true) with check (true);

drop policy if exists "Enable all for contacts" on public.order_contacts;
create policy "Enable all for contacts" on public.order_contacts for all using (true) with check (true);
