-- Tabela para registrar os aceites digitais
create table public.acceptance_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_id text not null,
  customer_name text not null,
  customer_document text not null,
  signer_name text not null,
  signer_email text not null,
  signature_hash text not null,
  user_agent text,
  ip_address text
);

-- Permissões (se RLS estiver habilitado)
alter table public.acceptance_logs enable row level security;

create policy "Enable insert for all users" on public.acceptance_logs
for insert with check (true);

create policy "Enable select for all users" on public.acceptance_logs
for select using (true);
