-- SCRIPT PARA CONFIGURAR STORAGE DE PDFs NO SUPABASE
-- Execute este script no SQL Editor do Supabase DEPOIS de criar o bucket 'order-pdfs'

-- 1. Criar política de leitura pública (qualquer um pode baixar)
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'order-pdfs' );

-- 2. Criar política de upload (apenas usuários autenticados podem fazer upload)
-- Como estamos usando anon key, vamos permitir insert para todos
CREATE POLICY "Allow Upload"
ON storage.objects FOR INSERT
WITH CHECK ( bucket_id = 'order-pdfs' );

-- 3. Criar política de delete (apenas admin pode deletar)
CREATE POLICY "Allow Delete"
ON storage.objects FOR DELETE
USING ( bucket_id = 'order-pdfs' );

-- 4. Adicionar colunas na tabela orders para armazenar URLs dos PDFs
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS pdf_url text,
ADD COLUMN IF NOT EXISTS pdf_generated_at timestamp with time zone;

-- 5. Criar tabela para logs de PDFs de aceite
CREATE TABLE IF NOT EXISTS public.acceptance_pdfs (
  id bigint generated by default as identity primary key,
  order_id text references public.orders(id) on delete cascade,
  pdf_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  signer_name text,
  signer_email text
);

-- 6. Habilitar RLS
ALTER TABLE public.acceptance_pdfs ENABLE ROW LEVEL SECURITY;

-- 7. Política de acesso
DROP POLICY IF EXISTS "Enable all for acceptance_pdfs" ON public.acceptance_pdfs;
CREATE POLICY "Enable all for acceptance_pdfs" ON public.acceptance_pdfs 
FOR ALL USING (true) WITH CHECK (true);
